### ISSUE TITLE
lazy loading

### ISSUE THREAD

**Issue by JLarky** [MattHalloran/Vrooli#12]
Hi guys :) I'm really glad that you are using my library (creator of react-lazily here, BTW), I just wanted to make sure that you are getting most out of it :)

So [here](https://github.com/MattHalloran/Vrooli/blob/4e10dad39cc02ed4dbe1591b980f26f89c0873e9/packages/ui/src/Routes.js#L32) in the code you have it like

```js
const { a, b, c} = lazily(() => import('./a_and_b_and_c'))
```
but expected usage is more like
```js
const { a } = lazily(() => import('./a'));
const { b } = lazily(() => import('./b'));
const { c } = lazily(() => import('./c'));
```

the first one could be desired sometimes if you want to bring the number of chunks in your bundle down :) so I just was curious if this is what you were doing here or not :)

the downside of importing `index.js` is that `import` is going to bring the whole file :)

so
```js
const { AboutPage } = lazily(() => import('./pages'));
```
will download the bundle for all pages, and
```js
const { AboutPage } = lazily(() => import('./pages/AboutPage'));
```
will download just the about page :)

I'm planning to improve docs and I want to cover that topic there, so I'm just gathering some feedback on how people use the library :)

**Comment by MattHalloran** [comment]
Hi @JLarky! Thank you for bringing this to my attention. I believe when I originally looked into lazy imports (for [another project](https://github.com/MattHalloran/ReactGraphQLTemplate)), I came across react-lazily because it offered a clean way to lazy import all of my pages. At the time, this seemed great because my project wasn't *that* large, and Lighthouse was bugging me about having too many chunks. I was doing so many different things to try to maximize my performance score, that I didn't have time to properly look into if I was lazy loading correctly.

Now that I'm working on a project with a lot more pages and components, it's about time that I looked back into this. The change you suggested is working swimmingly😁

One suggestion I have for your docs is to include an example of lazy loading routes like I'm doing. I ran into an issue today where - despite splitting the imports correctly - it still fetched every bundle. It was harder than it should have to discover that wrapping the entire switch in one suspense was the culprit (as opposed to the correct way of wrapping each page). That is probably obvious to people who were already familiar with lazy loading before stumbling across your project, but for someone like me who had just discovered lazy loading, having a full example would be really helpful.

Thanks again for submitting this issue! I just pushed the fix to the dev branch, and I don't plan on updating main until the Vrooli MVP launches next month, so I'm gonna close this issue now. If you'd like, feel free to check out our README to see what we're all about, and give this project a star/watch if you're feeling generous😊
